### ISSUE TITLE
background job ends immediately with or without timeout

### ISSUE THREAD

**Issue by james-cook** [matiasdelellis/facerecognition#146]
**Heads-up the pdlib install's "make test" does produce 5 fails out of 12** (see: https://github.com/goodspb/pdlib/issues/14) but I decided to see "how far" I could get despite this.
So... when I do: 
`sudo -u www-data php occ face:background_job`
the command returns almost immediately AFAICT without actually doing anything...
```
1/10 - Executing task CheckRequirementsTask (Check all requirements)
2/10 - Executing task CheckCronTask (Check that service is started from either cron or from command)
3/10 - Executing task LockTask (Acquire lock so that only one background task can run)
4/10 - Executing task DisabledUserRemovalTask (Purge all the information of a user when disable the analysis.)
5/10 - Executing task StaleImagesRemovalTask (Crawl for stale images (either missing in filesystem or under .nomedia) and remove them from DB)
6/10 - Executing task CreateClustersTask (Create new persons or update existing persons)
        Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
        * have 1000 faces already processed (you have 0),
        * have 100 images (you have 0),
        * or you need to have 95% of you images processed (you have 0.00%)
7/10 - Executing task AddMissingImagesTask (Crawl for missing images for each user and insert them in DB)
8/10 - Executing task EnumerateImagesMissingFacesTask (Find all images which don't have faces generated for them)
9/10 - Executing task ImageProcessingTask (Process all images to extract faces)
        NOTE: Starting face recognition. If you experience random crashes after this point, please look FAQ at https://github.com/matiasdelellis/facerecognition/wiki/FAQ
10/10 - Executing task UnlockTask (Release obtained lock)
```

i.e. 10/10 appears immediately - without any pause in step 9/10

When I re-run counts are still at zero -  

> "(you have 0)"

.

Is there any log file I can check which shows what is happening here?

**Comment by matiasdelellis** [comment]
Hi @james-cook 
Thank you for trying the application and participating here. :wink: 

Without going into details, please make a test, try forcing only analyze your user.

> sudo -u www-data php occ face:background_job -u YourNcUser

**Comment by matiasdelellis** [comment]
p.s: If you increase the Nextcloud debug ("loglevel" => "0" on config.php), you can see more information about process.

**Comment by stalker314314** [comment]
To jump in with two more points:
1. Add `-vvv` to `face:background_job` to get debug output (basically, same as what Matias said), e.g. `sudo -u www-data php occ face:background_job -vvv`
2. Task 9 could be failing because there is not enough memory, or because there is no images to scan faces for. Do you have any rows when connecting to DB and executing `select * from oc_face_recognition_images` where it is your user (column `user`) and `isProcessed` is false?
3. Are you using external mount, as this app is (currently) not working with external storages?

**Comment by matiasdelellis** [comment]
@james-cook 
Have you enabled the analysis to your user?
I see that it is not sufficiently clear. :disappointed: 

SInce https://github.com/matiasdelellis/facerecognition/pull/133 the analysis is disabled by default, and each user must enable it.

**Comment by james-cook** [comment]
> SInce #133 the analysis is disabled by default, and each user must enable it.

That seems to have done it!

**Comment by stalker314314** [comment]
@matiasdelellis Maybe we should write in regular log (not debug log) that we are skipping user X because analysis is disabled for him/her?

**Comment by james-cook** [comment]
I'd also suggest adding a line to the README just before the doc about the `occ face:background job` command...

**Comment by matiasdelellis** [comment]
> That seems to have done it! :)

Great, I hope you have good results and any report like this important, thank you!.. :smile: 

> @matiasdelellis Maybe we should write in regular log (not debug log) that we are skipping user X because analysis is disabled for him/her?

Now I do it in the memory-limits branch.

> I'd also suggest adding a line to the README just before the doc about the occ face:background job command...

Yes .. This is fundamental, and we should write the formal documentation to users.

**Comment by matiasdelellis** [comment]
What do you think?
https://github.com/matiasdelellis/facerecognition/pull/144/commits/fc0405c22e7de69e61865473d48afa662a2c7100

**Comment by matiasdelellis** [comment]
I just upload some screenshots here in order to write the documentation in wiki.

Main view disabled:
![imagen](https://user-images.githubusercontent.com/733715/58920134-38dc6700-8707-11e9-9c9a-6abcd596f561.png)

Main view with persons.
![imagen](https://user-images.githubusercontent.com/733715/58920240-95d81d00-8707-11e9-8efb-cd18b7147f42.png)

File pane details:
![imagen](https://user-images.githubusercontent.com/733715/58920409-6aa1fd80-8708-11e9-955d-dd993654be21.png)

Search by name in file app.
![imagen](https://user-images.githubusercontent.com/733715/58920458-ad63d580-8708-11e9-878c-69cad0d9c4b8.png)

**Comment by james-cook** [comment]
The wiki is very clear now

**Comment by james-cook** [comment]
Thanks BTW!
