### ISSUE TITLE
Feature: Able to move between groups or remove recognized faces. 

### ISSUE THREAD

**Issue by aleksandrmetik** [matiasdelellis/facerecognition#158]
Hello
Could you please implement action to move recognized faces between groups and/or remove from group? Thanks

**Comment by stalker314314** [comment]
This is similar to #134 . This will require another "layer" on top of basic clustering (manual layer) and we are not sure how to do it correctly. Manual actions (join clusters, move/remove face to group) needs to be preserved once new clustering is executed. There is no plans to do it soon

**Comment by matiasdelellis** [comment]
Hi @aleksandrmetik,
As Branko says, It is an expected feature of an application like this, and we have to do it right.

So, this will be for a second stage.. With enough external testing we must first ensure the stability of the clusters ... and seriously think about how to implement it.

**Comment by DerOetzi** [comment]
Hi @matiasdelellis,

for me a quick win would be to have the possibility in UI to untag (remove) single and complete groups of recognized faces completly from database, for two reasons:

- When I reduce sensitivity the clustering works very well for all of my friends, but there are always a few wrong faces in the cluster but mainly "unknown" persons from background, which I never want to be tagged. 
- For doing lot of pictures at the performance of my band there are lot of pictures of audience which are recognized as well and I want to remove them as well. Because they slow down clustering process unnecessarily. The initial scan process of my round about 20000 pictures is finished for about 70% and there are already 25.000 faces recognized. I restart background scan process every 60 minutes with a timeout of 58 minutes. Reclustering takes already about 10 minutes of each run. 

So I would request two feature:
- Remove recognized faces single and bulk.
- Requeue single picture for scanning, if I remove face accidentaly

**Comment by matiasdelellis** [comment]
Hi @DerOetzi 

Thank you very much for testing the application. :wink:

What I can tell you is that it is still under evaluation.  
Now we have a simple database where to store the face encodings, and the clustering algorithm that gave us the best result keeping the application simple.

I am 95% sure that the wrong people in your main groups are unknown. But it doesn't mix two persons who are really important to you. If so, it is within current expectations.

I clarify and ask this, because one thing is remove a person that you do not care (A small hack), and another very different problem is to separate a group into two people (An important rewrite.)

Again, of course we have to improve, but I want to advance at the right step, and therefore I am thinking it through. That is, I don't want to do a little hack to add this feature, and then have to undo it because I found a better way or it causes problems.

This will take some time.. Sorry.

As for clustering speed, I don't know which PDlib you are using, but if not, try to recompile this https://github.com/matiasdelellis/pdlib

**Comment by HollowedEmpire** [comment]
I second this feature. I have several incorrectly identified faces in groups - and I also additionally have one person split across multiple groups and would like them joined. I've tried fiddling with different sensitivity settings but to no avail.

**Comment by matiasdelellis** [comment]
Hi @HollowedEmpire 

> I second this feature.

Ok.. At some point this feature will be developed. :wink: 

> I have several incorrectly identified faces in groups - and I also additionally have one person split across multiple groups and would like them joined. I've tried fiddling with different sensitivity settings but to no avail.

The quality of current algorithm is a balance between the least amount of errors in a group, and the least amount of groups of the same person. With high sensitivity, there will be few groups but of poor quality. With a low sensitivity, there will be many groups, but of great quality. I guess this is well documented.

Well, having this, it is relatively easy to join groups, but it is still difficult to separate these.

So the question is... With some configuration you have good quality groups? Regardless of the number of groups.

**Comment by darmbrust** [comment]
Just commenting so I can follow this issue...looking forward to trying it out when an implementation is ready for testing.

Been playing with this plugin on my own pictures, and without the ability to "correct" the groupings, and move photos into the correct groupings / names, the results of running face recognition are too wrong for me currently.

**Comment by GAS85** [comment]
I made a mistake, I put to "to be checked" on different groups of people that I do not remember. But they were merged in 1 group "to be checked". Now there is no way to drop this group.

**Comment by matiasdelellis** [comment]
Hi @GAS85 
Go to the photos of the person "to be checked", and see below that you must have a button that says "See groups of faces" 😉

**Comment by GAS85** [comment]
You make my day! Thanks that's works good!!!

**Comment by guystreeter** [comment]
I don't know how I can help with this, not knowing PHP or js (or web servers in general) very well, but I *really* need to be able to correct the name for a person. I keep having to reset and start over completely because I entered the wrong name for someone.

I'll help anyway I can.

**Comment by matiasdelellis** [comment]
Hi,
Although there may be improvements, this feature can be considered implemented. Some options are better to see in memories.

Thanks for everything!. 😄
