### ISSUE TITLE
Feature: custom exclusion folder

### ISSUE THREAD

**Issue by millionart** [matiasdelellis/facerecognition#171]
I have some special folders for storing landscapes and emoticons. However, these images are still mixed with facial recognition results. I understand that facial recognition results are temporarily imperfect, so I hope to allow me to manually disable certain images from being analyzed.

This exclusion function is best to use the folder (total exclusion) and the label (individual exclusion) function.

**Comment by stalker314314** [comment]
Hi,
FaceRecognition do have something like what you need - if you place empty file in folder, named `.nomedia`, it will exclude that folder, as well as all children folders from face detection, completely. Furthermore, I think that application is smart enough that, moment that you place this file in some foldee, all images/faces under that folders will be deleted and clustering rescheduled! Would that work for you (to exclude folders with landscapes/emoticons)?

What is "label" (individual exclusion)? Excluding individual files? FaceRecognition definitely don't have that, not sure what @matiasdelellis thinks of adding it. To me, doesn't look like big issue and I am not even sure how to implement it without some custom logic.

P.S. I just realized that nowhere in wiki we are talking about this feature, so I'll add it - keep this issue active.

**Comment by millionart** [comment]
Thank you! It works!

**Comment by stalker314314** [comment]
I added explanation to:
https://github.com/matiasdelellis/facerecognition/wiki/Usage
https://github.com/matiasdelellis/facerecognition/wiki/FAQ
Will close task now:)

**Comment by berho** [comment]
Hello,
first of all: many thanks for the great job done on facerecognition!! I am on the way to run over > 300 GB of images (7 days left ;)

But I am not happy with the ".nomedia" file: I have folders containing lot of images I do not want to recognice faces on it (public events) but I want to view them with Gallery app! But when I place a file named ".nomedia" inside the folder it is not visible to Gallery anymore!

**Comment by matiasdelellis** [comment]
Ok @berho 
It seems a real case to improve .. :smile: 

I can't find the discussion, but at some point we talked about using a `.nofacemedia` file with the same purpose. 
It doesn't convince me 100%, but I suppose it is an easy solution to a real problem.

**Comment by stalker314314** [comment]
Maybe we can make it app (or user) config? Defaults to `.nomedia`, but user can change it to whatever they want (maybe keep it hidden and require to be a file)?

**Comment by matiasdelellis** [comment]
I am not sure about the name of the file but I would not make it configurable. 
As for the configuration, I can make a side panel on the folders where to enable analysis or not for this folder. That is more or less easy. But this should affect the creation of the `.nofacemedia` file or its deletion. I don't want to depend on any database for it.

If you want to go with an approach like #89, I don't have problems, but for now I would only add the detection:on/off option. (And by default be enabled.)

**Comment by stalker314314** [comment]
I agree with no dependency on DB. I agree supporting only detection on/off. I agree with UI to change it. But this is all orthogonal problem to name of file to ignore detection.

I am just saying we cannot just change `.nomedia` to `.nofacemedia`. (1) We already have it, so it is kind of backward-incompatible change, (2) We should honor existing practises, I would be annoyed if FaceRecognition app start going in my `.nomedia` folders, (3) it is principle of least suprise for users.

And I also think `.nomedia` should be default. Since we have one user that is not OK with `.nomedia`, but wants something else, and since we don't know if @berho is only one, or 50% of all people, this is why I think there are only two solutions:
1. Add user/app config to change what file name we are looking for and document how to change it, but keep it only for advanced users
2. Add support for hardcoded `.nofacemedia` and use it if either `.nomedia` or `.nofacemedia` exists (this could also work).

**Comment by millionart** [comment]
I had the same issue and would like to add an exclusion list on the UI.
I don't like the method of .nofacemedia files, because it will leave a residue when uninstalling (eg I don't need nextcloud someday)

**Comment by matiasdelellis** [comment]
> I don't like the method of .nofacemedia files, because it will leave a residue when uninstalling (eg I don't need nextcloud someday)

Although I agree in part, but this file will only exist in a main folder. Mac's DS_media or WIndows thumbs.db files are much more annoying.  :sweat_smile: 
It would be difficult for you to end up having a lot of junk files.. :wink: 

> And I also think .nomedia should be default. Since we have one user that is not OK with .nomedia, but wants something else, and since we don't know if @berho is only one, or 50% of all people, this is why I think there are only two solutions:
>
>    Add user/app config to change what file name we are looking for and document how to change it, but keep it only for advanced users
>    Add support for hardcoded .nofacemedia and use it if either .nomedia or .nofacemedia exists (this could also work).

I agree the .nomedia file is more or less a standard, and we must consider it. Any file below a folder with .nomedia, are files that the user does not want to see, and therefore should not be analyzed.
.nomediaface would be a file with the same logic, but that only affects our application.

So, we must consider both files, and if we add the configuration, it would only affect the .nofacemedia file.

**Comment by matiasdelellis** [comment]
Done as part of the shared-storage-experiments branch. What do you think?

@stalker314314 
Still no guarantees, but I will probably try to merge this branch. It will be disabled by default, and there will be no interface to activate it, so that it is clear that it is an experiment.
Then I comment on that pull request, but the idea is to move a lot of code within a service that cleans many other duplicate codes. Disabled this option, the operation is exactly the same as until now.

**Comment by matiasdelellis** [comment]
Hi everyone,
See PR #202 
Please try it and give your opinion .. :wink:

**Comment by matiasdelellis** [comment]
Done on last nightly version.. :wink: 
If need other improvements open new issues.. :smile:
