### ISSUE TITLE
`occ face:background_job` processes one image and immediately exists

### ISSUE THREAD

**Issue by agboom** [matiasdelellis/facerecognition#176]
I have the facerecognition app running on an Alpine image, built with [this Dockerfile](https://github.com/matiasdelellis/facerecognition/issues/175#issuecomment-554786383). The app is installed fine, but when running `occ face:background_job`, the application exists after processing one image. The app is enabled for a single user with some thousand images.

I have set given PHP the setting `memory_limit=4096M`.

The output of the background job:

```
1/10 - Executing task CheckRequirementsTask (Check all requirements)
	Found 4096 MB available to PHP.
2/10 - Executing task CheckCronTask (Check that service is started from either cron or from command)
3/10 - Executing task LockTask (Acquire lock so that only one background task can run)
4/10 - Executing task DisabledUserRemovalTask (Purge all the information of a user when disable the analysis.)
yielding
yielding
yielding
5/10 - Executing task StaleImagesRemovalTask (Crawl for stale images (either missing in filesystem or under .nomedia) and remove them from DB)
	Skipping stale images removal for user shanna as there is no need for it
	Skipping stale images removal for user ** as there is no need for it
	Skipping stale images removal for user admin as there is no need for it
6/10 - Executing task CreateClustersTask (Create new persons or update existing persons)
	Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
	* have 1000 faces already processed (you have 0),
	* have 100 images (you have 0),
	* or you need to have 95% of you images processed (you have 0.00%)
yielding
	0 faces found for clustering
	0 persons found after clustering
yielding
	Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
	* have 1000 faces already processed (you have 0),
	* have 100 images (you have 0),
	* or you need to have 95% of you images processed (you have 0.00%)
yielding
7/10 - Executing task AddMissingImagesTask (Crawl for missing images for each user and insert them in DB)
	Skipping image scan for user shanna that has disabled the analysis
	Skipping full image scan for user **
	Skipping image scan for user admin that has disabled the analysis
8/10 - Executing task EnumerateImagesMissingFacesTask (Find all images which don't have faces generated for them)
yielding
9/10 - Executing task ImageProcessingTask (Process all images to extract faces)
	NOTE: Starting face recognition. If you experience random crashes after this point, please look FAQ at https://github.com/matiasdelellis/facerecognition/wiki/FAQ
yielding
	Processing image **
	Image scaled from 5184x3456 to 2172x1448 (since max image area is 3145728 pixels^2)
```

These are my current admin settings for the app: 

![image](https://user-images.githubusercontent.com/1269113/69082857-3e253800-0a41-11ea-8af5-d86ff83771c6.png)

**Comment by agboom** [comment]
This issue seems similar: https://github.com/matiasdelellis/facerecognition/issues/147

The exception is that in the case of #147 the server crashes and in this case it doesn't. It just exits.

**Comment by agboom** [comment]
As an addition: the single image that the background job prints does not show any recognized faces in the file browser. Even if the image has a clear face.

**Comment by stalker314314** [comment]
Did it actually processed that one image or just crashed? Look in DB using this query:
```sql
select * from oc_face_recognition_images where is_processed=true
```

I highly doubt it processed even one image, it is more probably it just crashed. There is even a text 2 lines above saying:
> NOTE: Starting face recognition. If you experience random crashes after this point, please look FAQ at https://github.com/matiasdelellis/facerecognition/wiki/FAQ

Did you look at FAQ? Basically, it is very hard to debug problems like this, but it is usually related to badly built pdlib->dlib interface or just OOM - can you try running with 1GB in settings (or overriding ./occ command with `--max_image_area=100000` or something small like that? Let's start with those obvious:)

**Comment by agboom** [comment]
Thanks for your suggestions @stalker314314 

Changing the memory limit to 1024M fixed it! It's happily scanning away now.

**Comment by stalker314314** [comment]
Yeah, but it is not good situation:) Can you help us see why system determined that 4GB is good for you. Can you share amount of physical RAM and how much is given to php in php.ini (but in cli version of php.ini!). Not sure what else...what is your system load on that machine (`free -h`), just to see if there was memory pressure or something else. FaceRecognition app should be able to figure out (somehow...) that 4GB was not OK for your system, but it didn't. Problem with OOMs is that you can recover and try with less memory:F

**Comment by agboom** [comment]
Of course! I'll try some things.

> Can you help us see why system determined that 4GB is good for you. 

Can you elaborate a bit on this? What do you mean by system? How did your conclude that it determined that 4GB is good? I configured the memory limit in the php.ini to 4096M myself (that's why it says 4GB in the admin interface.

The amount of physical ram is 8GB, the amount given to PHP CLI was 4096M, now it's 1024M.

I'm not sure how to correctly draw memory statistics from my system, but I just ran `while true; do free -h >> /tmp/mem; done` while running the background job. The result is in the following gist. It's 16000 lines, apologies for that. Maybe I can make it smaller by sleeping a second between every iteration.

https://gist.github.com/agboom/842bd2e36e14779e7b50365f67b77afa

**Comment by matiasdelellis** [comment]
Youe have another limits due docker...
Use `docker stats`

**Comment by stalker314314** [comment]
> How did your conclude that it determined that 4GB is good?

I just saw your first output, in the beggining it says that app decided that it should use 4GB:)

> I'm not sure how to correctly draw memory statistics from my system, but I just ran while true; do free -h >> /tmp/mem; done

You didn't have to do this, I was asking average usage when recognition is *not* running (so system snapshot). But first line tells you are using 3.2 GB. If this is before recognition started, this would explain why 4GB is not enough - you already have 8GB-3.2GB=4.8GB of memory committed and PHP is trying to allocate (roughly) 4GB more and system fails. Not sure why swap didn't help you (do you have it?). If this is a case, I guess we are ready for (yet another) entry in FAQ:) If you have spare cycles, you can verify this theory by bumping it back to 4GB and shutting down other processes, so that you have more than 4.5GB free (if this is possible for your setup).

If my assumption is not correct (3.2GB is before you started recognition), I don't have good explanation:)

**Comment by agboom** [comment]
> I was asking average usage when recognition is not running

**Comment by agboom** [comment]
> I was asking average usage when recognition is not running
Sorry I misunderstood :see_no_evil:. Without facerecognition running, I have about 4.5GB available:

```
free --mega
              total        used        free      shared  buff/cache   available
Mem:           8163        2956         780         191        4426        4539
Swap:             0           0           0
```

I have no swap, so that explains why swap didn't help. If it would, I will configure it.

@matiasdelellis Good point, I forgot about `docker stats`. From this info I realized I can free up about 2GB by shutting down some containers (which I need later again, but it could be useful for testing).

**Comment by stalker314314** [comment]
> I have no swap, so that explains why swap didn't help. If it would, I will configure it.

Unless you have really, really small faces im images (small in pixels), you are completely fine setting face recognition to 2GB (and not 4GB). We just thought of 4GB as upper limit, not as "premium" setting. Plus, detection will be faster with 1-2GB:)

@matiasdelellis Can you think of any way we can be smarter about this? Should we query `free` from PHP or something similar and prevent usage if there is not enough memory in system? I would not do this, as this is all very fragile and looks like voodoo.

Another option would be to add another command, like `occ face:recommend_memory` or something like that, that could look like this:
```
> ./occ face:recommend_memory
Detecting memory setting...
    Found 8GB in system
    Found 4GB for PHP
    Current empty memory is 4.5GB
We recommend setting memory for Face Recognition app to 3.5GB. Do you want to apply this setting now [Y/n]?
```

Even without this, we can get into trouble with OOM.

What else I think we discussed before is to set some `oc_appconfig` value before we do detection and check in web interface (admin) that it is reset properly (detection finished without crash) (and of course, that detection is not ongoing).

**Comment by matiasdelellis** [comment]
Hi both,

> @matiasdelellis Can you think of any way we can be smarter about this? Should we query free from PHP or something similar and prevent usage if there is not enough memory in system? I would not do this, as this is all very fragile and looks like voodoo.

Consider the current memory load (`free`) is not useful because we cannot know if the current load is normal, or the server is empty or overloaded.
For the cpu, we have simple statistics (such as `cat /proc/loadavg`), but I don't know anything similar to memory that is our problem.

Given this, I insist that our problem ends up being documentation. These limits must be set by the server administrator knowing the server. Beyond our suggestion, they should do so responsibly.

> Another option would be to add another command, like occ face:recommend_memory or something like that, that could look like this:

At some point I wanted to do something like this. but not for memory, rather to control all the requirements.

Finally I intended to do some test scripts, similar to the ones we use here (https://github.com/matiasdelellis/facerecognition/issues/175#issuecomment-554747326)
But officially publish them, as a form of installation test, and also use it as a requirement for the issue template (https://github.com/matiasdelellis/facerecognition/issues/150)

Well .. That said, it doesn't seem bad to add it as a new command to simplify everything, but without limiting ourselves to the use of memory, also must checking versions, models, and doing some real test with some image..

> What else I think we discussed before is to set some oc_appconfig value before we do detection and check in web interface (admin) that it is reset properly (detection finished without crash) (and of course, that detection is not ongoing).

As you say it not has an default value, but it takes the value that calculate according to the installation.
https://github.com/matiasdelellis/facerecognition/blob/1cded9fa6bf30321c0f00fd64c1da0ae5b3d54e8/lib/BackgroundJob/Tasks/CheckRequirementsTask.php#L81

This is replaced with the configured only if there is a value greater than zero:
https://github.com/matiasdelellis/facerecognition/blob/1cded9fa6bf30321c0f00fd64c1da0ae5b3d54e8/lib/BackgroundJob/Tasks/CheckRequirementsTask.php#L111-L112

But I must recognize a problem I saw now... :sweat_smile: 

https://github.com/matiasdelellis/facerecognition/blob/79b05c9ae4f0e0cd44674cb768976edaf7e1a87b/lib/Controller/SettingController.php#L209-L214

As I show above, the background task uses the memory correctly, but the administration panel shows by default the maximum memory... :man_facepalming: 

This should be fixed to match the memory that the background task would use.

**Comment by matiasdelellis** [comment]
Hi @agboom 
I understand that this should be fixed. But if is necessary, please open it again. 

Thank you very much for everything!

**Comment by maxi1134** [comment]
I am having this issue with 16gb allocated to PHP and 10gb to face recognition.
