### ISSUE TITLE
Initial face preview generation hang Nextcloud

### ISSUE THREAD

**Issue by Petahh** [matiasdelellis/facerecognition#193]
Hello All, when I access the recognized face those little square previews of faces start to load for the very first time, often the whole instance of Nextcloud freeze.

I'm using debian/apache version of Nextcloud with MariaDB, Redis with 4GB of RAM.

So I found that when I go line by line it loads in mannered fashion, but If I maximize and it tries to load all of the previews at once (for the first time) it works only unlit eats all the memory then hangs. Is there any way how to pace these previews or pre-generate all manually?

**Comment by matiasdelellis** [comment]
Hello @Petahh 
You're right, today we don't have any cache implementation.

We originally intended to use the browser cache, but having the faces of all your photos in the browser can be questionable..

As you observed, they are dynamically loaded as you move the viewport, but the faces are so small that you easily have 100 faces in sight at all times (This is 100 calls in parallel to your server). and if you scroll to the end of the page, it will try to load all your faces, which can be an important load for your server.

In principle, I never wanted to cache the server side because I think that this view should not exist (It would be for a long discussion :wink: ), and writing millions of small images on your disk, also would be an important load for your server, since writing to disk is even more expensive..

Well, we currently use [Lozad.js](https://github.com/ApoorvSaxena/lozad.js) to load the images dynamically. My first idea would be to look for an alternative that limits the loading of images to a certain number in parallel, but of course it is not a real solution to the problem.

> it works only unlit eats all the memory then hangs.

Sorry for that! :sweat:

**Comment by Petahh** [comment]
No worries @matiasdelellis , I managed to generate all by slowly scrolling down in small window. Now it works like charm. It’s something which definitely needs to be improved for future.

**Comment by matiasdelellis** [comment]
Although it is difficult, if it advances, we can do something similar ..

https://github.com/nextcloud/server/pull/18210

**Comment by GAS85** [comment]
Why not to use standard Previews folder of Nextcloud and just added there face1.jpg, face2.jpg? There is a 1 Folder per picture with different previews.

**Comment by matiasdelellis** [comment]
Hi @Petahh @GAS85 
I have been working to eliminate the face view, in favor of an photos view reusing Nextcloud thumbnails, and it could dramatically help with this problem..  See # 433, I would appreciate tests and comments.. :smile:

**Comment by GAS85** [comment]
Could't find anything under #433...

**Comment by matiasdelellis** [comment]
Sorry.. 😅 
https://github.com/matiasdelellis/facerecognition/pull/336

**Comment by matiasdelellis** [comment]
The load is still high in some parts, but as for this report, I consider it fixed in last release..

Thanks for everything!!
