### ISSUE TITLE
Keep 128d vector in DB

### ISSUE THREAD

**Issue by stalker314314** [matiasdelellis/facerecognition#2]
For each analysed face/image. It seems more flexible and you can reuse it later (for chinese whispers) and know your progress on image processing? What do you think?

**Comment by matiasdelellis** [comment]
Hi @stalker314314 
Yes, This would be ideal.. It would save a lot of processing when new familiar faces are added. :wink: 
I had thought a lot, look for alternatives instead of adding 128 columns to the database. But I did not find anything better.. :sweat_smile: 

Just recently I met https://github.com/goodspb/pdlib, where are you helping.. 
With pleasure when can get the vector with the library, we incorporate it into this application and finally we publish it.. :smiley:

**Comment by stalker314314** [comment]
I also had some thoughts...tried contacting you over linkedin, but didn't reach you:) You are hiding your mail pretty good:) Can you ping me over mail (it's in github), so we can continue over there? Or whatever other way of dumping design questions of your project/dumping ideas you prefer?

**Comment by stalker314314** [comment]
Also closing this, as 128d vector is now in DB...in JSON though 😄 , but this will be in some other GH issue, closing this
