### ISSUE TITLE
Decide on minimum Nextcloud version

### ISSUE THREAD

**Issue by stalker314314** [matiasdelellis/facerecognition#24]
Data points (add more as we go):
* v14 has requirement on PHP>=7. This removes one dimension when we think about pdlib support
* v14 has QBMapper. Not really that important, but we duplicated frFindEntities functionality which we could remove if we require >=14
* v14 is fairly new and I guess people are still on old version. Not sure is there any way to see adoption

**Comment by matiasdelellis** [comment]
Hi @stalker314314 ,
Every time I'm more convinced that it should be NC 14 with php 7. Is there a code amount for php 7 (eg Return Type Declarations?), and at least to me, I do not have any server with NC <14 to ensure compatibility..

> v14 has requirement on PHP>=7. This removes one dimension when we think about pdlib suppor

What do you mean?

> v14 is fairly new and I guess people are still on old version. Not sure is there any way to see adoption

Except in service sales environments -Who should use the Production release channel- , I would say that most migrated or will do so soon.

> v14 has QBMapper. Not really that important, but we duplicated frFindEntities functionality which we could remove if we require >=14

Just notice this today, and I went a little crazy, because I thought they were older functions.. haha

**Comment by stalker314314** [comment]
>> v14 has requirement on PHP>=7. This removes one dimension when we think about pdlib suppor

> What do you mean?

If we deal with both PHP5 and PHP7, that means you need 2x more binaries for pdlib, one compiled for php5 and one for php7:) (this is what `phpize` is doing, I think). We already have another dimensions - operating system (.dll, .so, fedora/ubuntu...), compiled support for CUDA or not, and it is hard already - if we drop support for PHP5, it should be easier...

This is new app and we are not constrained by supporting older version in any way. New app, fresh start:) I think no one will miss support for <=v13:)

**Comment by stalker314314** [comment]
So, if you don't mind, I would bump version to 14, add php requirements to composer...start using QBMapper
