### ISSUE TITLE
Clarify migrate documentation

### ISSUE THREAD

**Issue by strugee** [matiasdelellis/facerecognition#317]
(Omitting the usual issue template since this is just a doc bug.)

The description of the migrate commands is a little unclear to me. It says:

> Always is recommended to analyze from scratch any configured model, but you can save a lot of time migrating it.

But what exactly is meant by this? Is it that you should migrate, and then reanalyze from scratch? What exactly does "migrate" mean here?

I can prepare a PR to the docs if it would be helpful. Cheers :-)

**Comment by matiasdelellis** [comment]
Hi @strugee 

> > Always is recommended to analyze from scratch any configured model, but you can save a lot of time migrating it.
>
> But what exactly is meant by this? Is it that you should migrate, and then reanalyze from scratch? What exactly does "migrate" mean here?

Ohh.. Trying to be concise, it may not be clear ..

The new migration command do that:
1. Take all the faces you got in a old model (Which is usually the hardest task).
2. It aligns the faces with its own landmark predictor, and gets the descriptor with new model.
3. Save the same faces, but with the new landmarks and the new descriptor in the new model.

This (Migrating faces) saves about 90% of the time, against if you had analyzed from scratch (Set new model and run background_job for all images).

Migrating from model 2 to model 1 gives excellent results, but there is some data degradation when getting the original faces, (The rectangles of the faces are calculated, and changing just one pixel can cause problems). Therefore you could have better results analyzing from scracth instead of migrating. The difference is very small, but it can happen. 

Well, but if you migrating to model 4, you will not have all the benefits of the new model, since the validation is done within the discovery stage and it is precisely the task that we are avoiding. So, if you migrate from model 2, you will still see very good results, but if you migrate from model 1, you will get practically the same results that you already had on the original model.

> I can prepare a PR to the docs if it would be helpful. Cheers :-)

As always welcome.. :smile: 
But it has to be concise in the readme. :wink:
