### ISSUE TITLE
Not working with unlimited memory_limit

### ISSUE THREAD

**Issue by escoand** [matiasdelellis/facerecognition#330]
### Expected behaviour
Set `memory_limit=-1` to allow PHP to use all available memory. This is maybe not the best way to work with PHP but it should be possible.

### Actual behaviour
Background job is complaining:
```
You do not meet the dependencies to install the model 1 (Default)
Summary: Your system does not meet the minimum memory requirements
Please read the documentation for this model to continue: https://github.com/matiasdelellis/facerecognition/wiki/Models#model-1
```

### Steps to reproduce
1. set `memory_limit=-1`
2. Try to start background job

**Comment by matiasdelellis** [comment]
Hi @escoand 
Among the considerations we made is that if you put unlimited memory, we restrict its use to half of the total for security.

You used a device with less than 2Gb of ram??? This is restricted to less than 1Gb and that's why it fails..
In your case, it causes problems, but it is a security consideration. 😞

**Comment by matiasdelellis** [comment]
p.s: Now that I remember, this is exactly why we used 2Gb before as limit. haha

**Comment by escoand** [comment]
No, the problem is not less than 2GB. When I set the value to 1GB, it's working. My system has exactly 2GB but not `2*1.024*1.024*1.024=2.147.483.648bytes` but some bytes less...

But `-1` is obviously not the best idea on a low powered system because the system was completely busy with swapping. So I'll close this issue.
