### ISSUE TITLE
Which model should be used?

### ISSUE THREAD

**Issue by ntimo** [matiasdelellis/facerecognition#370]
### Expected behaviour

The documentation https://github.com/matiasdelellis/facerecognition/wiki/Models#install-models should point out which model is best practise for the facerecognition app and should therefore be used in ideal setups. This will make it easier to setup the app and help new users

### Actual behaviour

The user has to figure which model to use for example the usage of model 2 is discouraged, so there are still model 1 3 and 4. But the docs do not state which of these 3 models should be used, so its quite hard to figure out which one will return the best results.

**Comment by matiasdelellis** [comment]
Hi @ntimo 
The problem is that it is still personal, and it depends on each person and server resources.. That's why I only show the summary table (Although model 4 is missing)

In general:
* If you have few resources, use model 3 (HOG): You will find 70% of the faces, but the results will be very good with less than 150MB of ram
* If you have enough resources, and time, use model 4 (CNN-HOG): It needs lot of more ram, it is slower, but it finds most of the faces with an excellent result.
* If you are anxious, and want the most faces, use model 1. It consumes the same amount of ram as the model 4, is faster, and offers quite good results, but certainly the Model 4 is just a bit better.

**Comment by matiasdelellis** [comment]
ps. : Formally the model 4 is in the testing stages, but personally it is the one that I recommend.

See for deails:
https://github.com/matiasdelellis/facerecognition/pull/313
