### ISSUE TITLE
Change order of face recognition

### ISSUE THREAD

**Issue by cliffalbert** [matiasdelellis/facerecognition#371]
This is more of a feature request then a bug. But it would be nice to first check for new image/faces and after that do the createclusterstask. 

I think this behaviour was build this way due to the face recognition running from a cron job. But in my case it is usually run manually.

The problem is that when first running CreateClusterTask and then looking for new images is that in practice you have to run the background job twice before pictures start to show up in the face recognition web interface.

Maybe this behaviour could be introduced using an addition flag ? Like --check-new-first ?

**Comment by matiasdelellis** [comment]
Hi @cliffalbert 

It is in consideration.
In general, I would think about switching these tasks when time is not indicated. So, if you indicate time, it is because you have it as a scheduled task, and If you did not indicate a time limit, it is because at the end you expect to see the result when finish the command.

However, you will understand that it is not within the priorities. 🙈 
Thanks for the report. 😬

**Comment by cliffalbert** [comment]
Let me fiddle around with changing the order when timeout is 0, as far as I can see it wouldn't be that hard to implement. If I get it working correctly expect a PR ;)

**Comment by matiasdelellis** [comment]
Great @cliffalbert 
I want to wait for a comment from Branko but it looks good.. Thanks.

**Comment by matiasdelellis** [comment]
Hi @cliffalbert
Merged on master... 
Thanks for all.. :wink:
