### ISSUE TITLE
Systematic crash when running background job, gets worse with more processed pictures

### ISSUE THREAD

**Issue by ozls** [matiasdelellis/facerecognition#428]
### Expected behaviour

`occ face:background_job` should keep working until all images are processed or time limit is reached.

### Actual behaviour

`occ face:background_job` stops working after less and less image as more image are processed, until it is not possible to run anymore

### Steps to reproduce
1. Process around 30,000 pictures
2. Run `occ face:background_job`

### Server configuration

* **Operating system:** Raspbian 10 (buster) arm64

* **Pdlib version:** 1.0.2

* **How is DLib installed:** Built using the instructions from Github

* **How is PDlib installed:** Built using the instructions from Github

* **PHP version:** 7.4.13

* **Web server:** Apache 2

* **Database:** MySQL 10.3.27

* **Nextcloud version:** 20.0.6

#### Background task log with debug.
<details>
<summary>sudo -u php -f occ face:background_job</summary>

```
Processing image /var/nextcloud/data/picture.jpg
An unhandled exception has been thrown:
Error: Call to a member function file_get_contents() on null in /var/www/nextcloud/lib/private/Files/Filesystem.php:716
Stack trace:
#0 /var/www/nextcloud/lib/private/legacy/OC_Image.php(624): OC\Files\Filesystem::file_get_contents('/var/nextcloud/...')
#1 /var/www/nextcloud/apps/facerecognition/lib/Helper/TempImage.php(112): OC_Image->loadFromFile('/var/nextcloud/...')
#2 /var/www/nextcloud/apps/facerecognition/lib/Helper/TempImage.php(71): OCA\FaceRecognition\Helper\TempImage->prepareImage()
#3 /var/www/nextcloud/apps/facerecognition/lib/BackgroundJob/Tasks/ImageProcessingTask.php(203): OCA\FaceRecognition\Helper\TempImage->__construct('/var/nextcloud/...', 'image/png', 734400, 512)
#4 /var/www/nextcloud/apps/facerecognition/lib/BackgroundJob/Tasks/ImageProcessingTask.php(123): OCA\FaceRecognition\BackgroundJob\Tasks\ImageProcessingTask->getTempImage(Object(OCA\FaceRecognition\Db\Image))
#5 /var/www/nextcloud/apps/facerecognition/lib/BackgroundJob/BackgroundService.php(120): OCA\FaceRecognition\BackgroundJob\Tasks\ImageProcessingTask->execute(Object(OCA\FaceRecognition\BackgroundJob\FaceRecognitionContext))
#6 /var/www/nextcloud/apps/facerecognition/lib/Command/BackgroundCommand.php(138): OCA\FaceRecognition\BackgroundJob\BackgroundService->execute(0, false, NULL, NULL)
#7 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\FaceRecognition\Command\BackgroundCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1000): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/nextcloud/3rdparty/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(OCA\FaceRecognition\Command\BackgroundCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/nextcloud/3rdparty/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#13 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#14 {main}%
```
</details>

**Comment by ozls** [comment]
I noticed this happens mainly with incorrect JPG files. The worsening behavior could be explained by the fact that, after having processed all correct files, there remains only the incorrect ones. In my case, my suspicion is the the responsible incorrect files are created during the upload because of  the "motion pictures" feature of Google Camera. These pictures often have "MVIMG" in their names. Nevertheless, the correct behavior should be to detect incorrect formats and to ignore those files.

**Comment by Krumbelfix** [comment]
After brute-forcing with the following script it failes to process the last image:
**brute-force:**

```
#/bin/bash

while  true
do
	docker exec --user www-data nextcloud php occ face:background_job -t 900
	sleep 1	
done
```


**Result:**
`Analyzing images - 79044 images detected - 1 image in queue - Ends approximately in ein paar Sekunden`
But processing the last image never stops.
I get this error:

> 1/10 - Executing task CheckRequirementsTask (Check all requirements)
2/10 - Executing task CheckCronTask (Check that service is started from either cron or from command)
3/10 - Executing task LockTask (Acquire lock so that only one background task can run)
4/10 - Executing task DisabledUserRemovalTask (Purge all the information of a user when disable the analysis.)
5/10 - Executing task StaleImagesRemovalTask (Crawl for stale images (either missing in filesystem or under .nomedia) and remove them from DB)
6/10 - Executing task CreateClustersTask (Create new persons or update existing persons)
	Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
	* have 1000 faces already processed
	* or you need to have 95% of you images processed
	Use stats command to track progress
	Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
	* have 1000 faces already processed
	* or you need to have 95% of you images processed
	Use stats command to track progress
	Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
	* have 1000 faces already processed
	* or you need to have 95% of you images processed
	Use stats command to track progress
	Clusters already exist, estimated there is no need to recreate them
	Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
	* have 1000 faces already processed
	* or you need to have 95% of you images processed
	Use stats command to track progress
	Skipping cluster creation, not enough data (yet) collected. For cluster creation, you need either one of the following:
	* have 1000 faces already processed
	* or you need to have 95% of you images processed
	Use stats command to track progress
7/10 - Executing task AddMissingImagesTask (Crawl for missing images for each user and insert them in DB)
	Skipping image scan for user user0 that has disabled the analysis
	Skipping image scan for user user1 that has disabled the analysis
	Skipping image scan for user user2 that has disabled the analysis
	Skipping image scan for user user3 that has disabled the analysis
	Skipping image scan for user user4 that has disabled the analysis
8/10 - Executing task EnumerateImagesMissingFacesTask (Find all images which don't have faces generated for them)
9/10 - Executing task ImageProcessingTask (Process all images to extract faces)
	NOTE: Starting face recognition. If you experience random crashes after this point, please look FAQ at https://github.com/matiasdelellis/facerecognition/wiki/FAQ
	Processing image <path-to-image>200116200302_30472.jpg
An unhandled exception has been thrown:
Error: Call to a member function file_get_contents() on null in /var/www/html/lib/private/Files/Filesystem.php:716
Stack trace:
#0 /var/www/html/lib/private/legacy/OC_Image.php(624): OC\Files\Filesystem::file_get_contents('/var/www/html/d...')
#1 /var/www/html/custom_apps/facerecognition/lib/Helper/TempImage.php(112): OC_Image->loadFromFile('/var/www/html/d...')
#2 /var/www/html/custom_apps/facerecognition/lib/Helper/TempImage.php(71): OCA\FaceRecognition\Helper\TempImage->prepareImage()
#3 /var/www/html/custom_apps/facerecognition/lib/BackgroundJob/Tasks/ImageProcessingTask.php(203): OCA\FaceRecognition\Helper\TempImage->__construct('/var/www/html/d...', 'image/png', 786432, 512)
#4 /var/www/html/custom_apps/facerecognition/lib/BackgroundJob/Tasks/ImageProcessingTask.php(123): OCA\FaceRecognition\BackgroundJob\Tasks\ImageProcessingTask->getTempImage(Object(OCA\FaceRecognition\Db\Image))
#5 /var/www/html/custom_apps/facerecognition/lib/BackgroundJob/BackgroundService.php(120): OCA\FaceRecognition\BackgroundJob\Tasks\ImageProcessingTask->execute(Object(OCA\FaceRecognition\BackgroundJob\FaceRecognitionContext))
#6 /var/www/html/custom_apps/facerecognition/lib/Command/BackgroundCommand.php(138): OCA\FaceRecognition\BackgroundJob\BackgroundService->execute(900, false, NULL, NULL)
#7 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OCA\FaceRecognition\Command\BackgroundCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/3rdparty/symfony/console/Application.php(1000): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/3rdparty/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(OCA\FaceRecognition\Command\BackgroundCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/3rdparty/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/console.php(100): OC\Console\Application->run()
#13 /var/www/html/occ(11): require_once('/var/www/html/c...')
#14 {main}

**Comment by ramomonalbertov** [comment]
Same error, just stuck on 6 images left.

**Comment by ramomonalbertov** [comment]
> Same error, just stuck on 6 images left.

I just disable an re-enable the option, and it finish!

![image](https://user-images.githubusercontent.com/850212/108653226-ad8ba200-74a4-11eb-82d9-b9a297a358d9.png)

**Comment by matiasdelellis** [comment]
Hi #428
Close it as dup of #295
I hope I can improve it soon... :wink:
