### ISSUE TITLE
PersonMapper is wrom?

### ISSUE THREAD

**Issue by matiasdelellis** [matiasdelellis/facerecognition#47]
See:

> https://github.com/matiasdelellis/facerecognition/blob/master/lib/Db/PersonMapper.php#L38

It is associated with the Image entity.. :confused:

**Comment by stalker314314** [comment]
Ops, sorry about this, fixed!
(this is what you get for copy/pasting stuff:D)

**Comment by matiasdelellis** [comment]
Geat, but in spite of that, the mapper was being used and worked correctly.

**Comment by matiasdelellis** [comment]
Just reopen until we're sure everything is working correctly.

**Comment by stalker314314** [comment]
It was working because this parameter (`entityClass`) is only needed if we are doing actual mapping, from columns to class fields (`mapRowToEntity`), and then mapper needs to now exact class it is going to instantiate and set fields to. This applies to generic methods, like `findEntities` etc. I was not using those generic methods and hence, I never noticed my copy-pasta:) I will still leave to you to close issue, if my explanation makes sense to you:)

**Comment by matiasdelellis** [comment]
OK .. Beyond that you convinced me, try "the whole circuit" and it works correctly.. :wink:
