### ISSUE TITLE
Please add compatibility with NC 22

### ISSUE THREAD

**Issue by elpraga** [matiasdelellis/facerecognition#500]
I believe the title is self explanatory.

BTW, thank you for taking my precious report with a bit of humor 😊 I did not notice that I had pasted a completely unrelated text. 🙄

**Comment by matiasdelellis** [comment]
Hi @elpraga 

I couldn't test it, because I'm still on NC21... but since https://github.com/matiasdelellis/facerecognition/pull/497 i release the version v0.8.3 that enables it ..

Like I said, I can't test it yet ... So if you tell me it's not working, we can try to make it work.

> BTW, thank you for taking my precious report with a bit of humor blush I did not notice that I had pasted a completely unrelated text. roll_eyes

haha.. Dont worry.. 😉

**Comment by elpraga** [comment]
I'm still on NC21 as well as there are several apps I use intensively that are still missing an update. I'll keep in mind that your latest update should work, and as soon as I update to NC22, I'll test it!

**Comment by elpraga** [comment]
I've just updated to NC22. 

I can confirm the Face Recognition app working as expected.

**Comment by guystreeter** [comment]
Should this be working now? I just pull the latest Nextcloud apache docker image, and get
```
Column "oc_facerecog_persons"."is_valid" is type Bool and also NotNull, so it can not store "false".
```
when I try to enable it in the web interface  or occ  command.
