### ISSUE TITLE
Add Support for nextcloud 24

### ISSUE THREAD

**Issue by jakobroehrl** [matiasdelellis/facerecognition#570]
https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

**Comment by guystreeter** [comment]
Do you know of any breaking changes in 24 that might affect face recognition?

**Comment by TylerVigario** [comment]
[Possibly, but doubtful](https://github.com/nextcloud/server/issues/29914)

**Comment by elpraga** [comment]
Yep, support for NC24 would be greatly appreciated.

**Comment by adeepn** [comment]
with ubuntu 22.04 and NC24 support for php 8.1 is needed

**Comment by matiasdelellis** [comment]
Hi all,
Some notes..

In general, except for #574 (Fix on https://github.com/matiasdelellis/facerecognition/pull/575/commits/0bc2b115945a6716fad0d4b08f4ae2e0491e8e31), it seems that support NC24... Please test and confirm..

About php 8.1, this app passes the lint test, but I understand that probably Nextcloud is not even ready for it. See https://github.com/nextcloud/server/issues/29287  among many other reports. 

About Ubuntu 22.04, note that my repository (Used in that script) does not have packages for this version. But there you absolutely no need to upgrade to this LTS when the old one is still supported until at least 2025.

Please be patient... There is no any reason to upgrade as soon as new versions come out. It never brings good results!. 🙈

**Comment by enoch85** [comment]
Nextcloud 24 works fine with PHP 8.1. 👍🏻

So now the questions remains when you will push repos for jammy (22.04) 🙃

**Comment by matiasdelellis** [comment]
Ok.. One step at a time... 
We have a repository for ubuntu jammy and dlib package..

```
echo "deb https://repo.delellis.com.ar jammy jammy" > /etc/apt/sources.list.d/20-pdlib.list
wget -qO - https://repo.delellis.com.ar/repo.gpg.key | sudo apt-key add -
apt update
apt install libdlib-dev
```

To achieve that, I had to prepare an entire development environment (which I already have working elsewhere, but ubuntu now uses Zstd, and basically it doesn't work anywhere other than ubuntu > 21.10). :flushed:
Then, first I try to compile pdlib using the official ubuntu package, and obviously it fails because the ubuntu package doesn't add the f**g pkg-config file. :weary: (the dev package is almost useless)

Well.. I compile dlib again and seems that work. 🤔 
I copy this to my repository server, add the distribution to reprepro, and try to add the package to that, and as obviously it couldn't be easy, it failed because reprepro doesn't understand Zstd packages either.. :tired_face:

Well. I go back to my original packaging environment, I have to repackage reprepro with Zstd support.. Luckily it compiled correctly, but being a sensible component, you never know. 🤔
I copied it to my server, installed it with my fingers crossed and it seems to work. 🎉  (I still don't know if I broke something else 😅)

So, I was able to add the dlib package, and with that, if I'm in a better mood 🙈 (and have time 😅 ), I compile pdlib using that package that just uploaded. :tired_face:

Please at least test that the repository works and that package can be installed. 🙏🏻 

p.s: Excuse the catharsis, (and believe me that this is summarized). haha

**Comment by matiasdelellis** [comment]
Well.. I woke up in a better mood.. 😅 
... and did the `php8.1-pdlib` package.. 😄 

```
echo "deb https://repo.delellis.com.ar jammy jammy" > /etc/apt/sources.list.d/20-pdlib.list
wget -qO - https://repo.delellis.com.ar/repo.gpg.key | sudo apt-key add -
apt update
apt install php8.1-pdlib
```

**Comment by TylerVigario** [comment]
@matiasdelellis Is an RPM for Fedora 36 in the works?

**Comment by matiasdelellis** [comment]
@TylerVigario 
https://copr.fedorainfracloud.org/coprs/matias/dlib/

😉

**Comment by TylerVigario** [comment]
```bash
[root@tylervigario ~]# dnf install pdlib
Last metadata expiration check: 0:22:44 ago on Sat 14 May 2022 01:31:55 PM PDT.
Error:
 Problem: conflicting requests
  - nothing provides libdlib.so.19.22.0()(64bit) needed by pdlib-1.0.2-4.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
[root@tylervigario ~]#
```

**Comment by matiasdelellis** [comment]
@TylerVigario
Ohhh..  Try again.. Maybe you should clear dnf cache since it is the same version.

**Comment by enoch85** [comment]
This is now implemented in the [Nextcloud VM.](https://github.com/nextcloud/vm)

**Comment by TylerVigario** [comment]
@matiasdelellis  I've cleared dnf cache. Please look at your repository. It does not include the requested version.

**Comment by matiasdelellis** [comment]
> @matiasdelellis Forget my original comment! It works now!

I had to recompile as you pointed out, but to make it fast I didn't even bother to change the version of the package. 😅 

Thanks to everyone!.

**Comment by matiasdelellis** [comment]
Hi @guystreeter 

> The official Docker image for Nextcloud 24 runs Debian Bullseye, but has PHP 8.0.18. Is it possible for you to pre-build pdlib for that?

Well, it is impossible make a pdlib package when inside the docker image they don't use official repositories.. For my part, what I can offer you is the dlib package that works in Bullseye, and compiling pdlib against that is relatively easy.

See:
 * https://github.com/matiasdelellis/facerecognition/wiki/PDlib-Installation#debian-bullseye (Install dlib insted php7.4-pdlib
 * https://github.com/matiasdelellis/facerecognition/wiki/PDlib-Installation#install-pdlib
 * https://github.com/matiasdelellis/facerecognition/wiki/Docker

NOTE: Obviously it's not impossible, but it doesn't make sense, since there is no control over dependencies which is essential for a package system to work.

p.s: I'm not an docker fan for services as Nextcloud, so I was never able to document it well, but docker-php-ext-install seems to simplify everything.

**Comment by matiasdelellis** [comment]
@guystreeter 

```
FROM nextcloud:apache

RUN apt update
RUN apt install -y wget gnupg2 unzip
RUN echo "deb https://repo.delellis.com.ar bullseye bullseye" > /etc/apt/sources.list.d/20-pdlib.list
RUN wget -qO - https://repo.delellis.com.ar/repo.gpg.key | apt-key add -
RUN apt update
RUN apt install -y libdlib-dev

RUN wget https://github.com/goodspb/pdlib/archive/master.zip \
  && mkdir -p /usr/src/php/ext/ \
  && unzip -d /usr/src/php/ext/ master.zip \
  && rm master.zip
RUN docker-php-ext-install pdlib-master

RUN apt-get install -y git wget
RUN git clone https://github.com/matiasdelellis/pdlib-min-test-suite.git \
    && cd pdlib-min-test-suite \
    && make
```

😉

**Comment by enoch85** [comment]
@matiasdelellis I must say, you're an amazing maintainer!

**Comment by mrAceT** [comment]
I am running AlmaLinux. Any chance of a pdlib "dnf installer" for PHP version 8.1 ?

```
# dnf search pdlib | grep php
Last metadata expiration check: 3:07:51 ago on Thu 29 Dec 2022 01:36:30 PM CET.
php70-php-pdlib.x86_64 : A PHP extension for Dlib
php71-php-pdlib.x86_64 : A PHP extension for Dlib
php72-php-pdlib.x86_64 : A PHP extension for Dlib
php73-php-pdlib.x86_64 : A PHP extension for Dlib
php74-php-pdlib.x86_64 : A PHP extension for Dlib
php80-php-pdlib.x86_64 : A PHP extension for Dlib
```

**Comment by dibya-ikea** [comment]
echo "deb [arch=amd64] https://repo.delellis.com.ar jammy jammy" > /etc/apt/sources.list.d/20-pdlib.list
wget -qO- https://repo.delellis.com.ar/repo.gpg.key | sudo tee /etc/apt/trusted.gpg.d/pdlib.asc


Seems the repo is down?
I keep getting 404

**Comment by enoch85** [comment]
@dibya-ikea https://github.com/matiasdelellis/facerecognition/issues/631
