### ISSUE TITLE
Easier installation

### ISSUE THREAD

**Issue by k0stya63** [matiasdelellis/facerecognition#632]
Hi all. I've been messing around with the app for hours and can't seem to install it. Is there a video tutorial or something easier, I can't get it to work ????
ps I couldn't get it to work with the instructions on githab ((

**Comment by opi1994** [comment]
Hi, would you like to tell us something about your system? Which OS, docker, error messages?
The installation is a bit difficult, but the Wiki page on GitHub should provide enough information about installation.

**Comment by matiasdelellis** [comment]
Hello,
Unfortunately it has its quirks, and you have to get your hands dirty. If you want help, it would be better if you explain at least what you use, and in which part of the process you stayed. 🤔

**Comment by Hainer1** [comment]
I am not sure if the first commenter here has the same problem, but I am struggling too.
I am following this link: [(https://github.com/matiasdelellis/facerecognition/wiki/Installation)]
Then to: [https://github.com/matiasdelellis/facerecognition/wiki/PDlib-Installation]
I follow the instructions for Ubuntu Jammy.
Then there is a gap in the section for me:
PDlib configuration 
Since I have php 8.1, where should I change php.ini?
I have tried nano /etc/php/8.1/cli/php.ini
and copying the two lines at the bottom of the file:
[pdlib]
extension="pdlib.so"

But then I get the following result:

root@nextcloud:~/dlib/dlib/build# php -m | grep pdlib
PHP Warning:  Module "pdlib" is already loaded in Unknown on line 0
pdlib

I expect more gaps but first I have to solve this I think
