### ISSUE TITLE
installation with php 8.2 (Nextcloud 26+)

### ISSUE THREAD

**Issue by johnhelt** [matiasdelellis/facerecognition#693]
This is not really an issue, but I wasn't sure where to put this, so here goes: 

When updating to nextcloud 26, the php is also updated to 8.2.x. This breaks the installation of pdlib inside docker! I found out as nextcloud was saying pdlib wasn't installed.
The error code you receive when building with docker-php-ext-install is:

#error "DLIB_NO_GUI_SUPPORT is defined so you can't use the GUI code. Turn DLIB_NO_GUI_SUPPORT off if you want to use it."

After a bit of experimentation, I propose this new recipe for building pdlib, which is needed for face recognition:

```
sudo apt update \
  && sudo apt install -y wget gnupg2 unzip

# install dlib

sudo apt-get install libx11-dev -y

git clone https://github.com/davisking/dlib.git
cd dlib/dlib
mkdir build
cd build
cmake -DBUILD_SHARED_LIBS=ON ..
make
sudo make install

# Install pdlib extension

wget https://github.com/goodspb/pdlib/archive/master.zip \
  && mkdir -p /usr/src/php/ext/ \
  && unzip -d /usr/src/php/ext/ master.zip \
  && rm master.zip
docker-php-ext-install pdlib-master

sudo apt-get install -y libbz2-dev
docker-php-ext-install bz2

# Increase memory limits
echo memory_limit=1024M > /usr/local/etc/php/conf.d/memory-limit.ini

# These last lines are just for testing the extension.. You can delete them.
wget https://github.com/matiasdelellis/pdlib-min-test-suite/archive/master.zip \
  && unzip -d /tmp/ master.zip \
  && rm master.zip
cd /tmp/pdlib-min-test-suite-master \
    && make
```

I ran the test-suite without any problems. I hope this is useful for someone here who experienced the same issues. Feel free to add this to the wiki. 
Thanks for a great job with the app and I hope the work is continued !

**Comment by johnhelt** [comment]
Yes, sorry for not mentioning that

**Comment by kabaga** [comment]
Do you know how to do  if there is a similar approach for a full VM instance?

**Comment by samssausages** [comment]
@johnhelt hey thanks for this, it's the first build I found that actually works with 8.2php and nextcloud 27.
I turned this into a dockerfile and added some other things like ffmpeg.  Hopefully it helps someone.

https://github.com/samssausages/nextcloud-dlib-pdlib-ffmpeg/tree/main

**Comment by P0Pss** [comment]
Hey,
I've tried all of the suggestions in the thread and haven't managed to get any of them working. The tests seem to go fine but whenever I try to select model 1 I always get the response that the PDlib PHP extension is not loaded.
Any ideas?

**Comment by samssausages** [comment]
> I always get the response that the PDlib PHP extension is not loaded. Any ideas?

Make sure that pdlib is referenced in your php.ini file.

check if it's loading pblib with:
`php -m | grep pdlib`
if that comes back blank, then it didn't find it as loaded.

Are you using a docker image?

The reason the instructions are conflicting online is because a lot of the instructions reference the php.ini file, but nextcloud docker doesn't have a php.ini file, it builds the file using a series of docker-php-ext-xxxx.ini files located in /usr/local/etc/php/conf.d/docker-php-xxxx.ini

If you have a php.ini file, you need to make sure it's added to your php.ini file like this:
```
[pdlib]
extension=\"pdlib.so\
```

If you don't have a php.ini file and have conf.d/docker-php-ext.ini files instead, then you need to create this file:
/usr/local/etc/php/conf.d/docker-php-ext-pblib.ini

and add this code to it:
```
[pdlib]
extension=\"pdlib.so\
```

my docker file build here already includes it and so far is working for me:
https://github.com/samssausages/nextcloud-dlib-pdlib-ffmpeg/tree/main

**Comment by P0Pss** [comment]
It is coming back blank. I am actually using your dockerfile!
Maybe a stupid question, but do I need to actively make the /usr/local/etc/php/conf.d folder and create the .ini file? I tried without making it which didn't work, I then tried manually creating the folder and file, as well as adding the code to it manually. But it also didn't work.
I'm wondering if I missed a step. Should it work by just adding your Dockerfile to the docker-compose.yml?

**Comment by P0Pss** [comment]
@samssausages Thank you so much for your help!!
Thanks to you I've realized I'm just stupid...
I did not realize that the dockerfile should be run instead of pulling nextcloud, so I ended up running both at the same time, so I could of course find the file when running from the other container. I've fixed the problem now and it works...
I've only just started using docker so really sorry about that hehe

**Comment by samssausages** [comment]
@P0Pss if you have any problems with my dockerfile or image, open an issue on my github.
https://github.com/samssausages/nextcloud-dlib-pdlib-ffmpeg/tree/main

**Comment by P0Pss** [comment]
@samssausages Thanks, really appreciate it!

**Comment by kurzer90** [comment]
Hi all,
having the issue that pdlib is not running under 8.2.
I'm not using docker. Tried a lot of thinks but it doesn't work. It always ends up with the following:

_PHP Warning:  PHP Startup: pdlib: Unable to initialize module
Module compiled with module API=20210902
PHP    compiled with module API=20220829
These options need to match
 in Unknown on line 0

You do not meet the dependencies to install the model 1 (Default)
Summary: The PDlib PHP extension is not loaded
Please read the documentation for this model to continue: https://github.com/matiasdelellis/facerecognition/wiki/Models#model-1_

Can somebody point me in the right direction?

**Comment by Cebrain** [comment]
@johnhelt 
thank you very much, configured your settings in my dockerfile and finally it is working again.

**Comment by matiasdelellis** [comment]
Thank you all. The application and pdlib work correctly in php 8.2 and up to nc28. 😬 😃 ❤️
