### ISSUE TITLE
Big Cluster / Face Group appeared with different People

### ISSUE THREAD

**Issue by Cebrain** [matiasdelellis/facerecognition#730]
### Problem
I updated in the last months to Nextcloud 28 and in the last days i found an big cluster /face group with all kind of people and images.
Example, the biggest cluster in my library is myself with 1300 photos and this appeared cluster are now 900 faces which includes pictures of myself and many other people i already identified as persons.

### Steps to reproduce
Sorry, i have no idea.

### Question

My question is now, is there a way to delete this Cluster/ Face group and rescan this pictures?
As i see i can add this group to another person, but this does not help because it is completely mixed.

**Comment by matiasdelellis** [comment]
Hi @Cebrain 
First of all, it would be important to know if you are using the "native" application in the user preferences or Memories.

The native tool is only preserved because there is an option to see the clusters that make up the person. Maybe there is a group of faces that you accidentally incorporated into the main person.

**Comment by Cebrain** [comment]
Hi,
i am not exactly sure what you mean with native application, but i think i am using the correct one in settings.

Example i the person to "Everyone?"
I went into Personal Settings -> Face Recognition -> Click on Face Group -> Review Facegroup 
I can only see one single face group.

In this group are now many faces with different people, most people i have already setup some persons.
![image](https://github.com/matiasdelellis/facerecognition/assets/78339531/2b187b3b-da10-4872-bf27-6b05fa2c7f18)

**Comment by matiasdelellis** [comment]
ok.. You have two options..
If you have faces with strange positions (Not frontal) and you are using model 1, I recommend using model 4 and you will have much better results.

If they are childrens, or non-Caucasian/Asian people, the model we use has problems identifying these people. This model simply cannot differentiate them well.. 🤦🏻  It is a big problem but there is still no better model.  😞 

In both cases you can try to reduce the grouping threshold and the minimum confidence and recluster again.

Then, just assuming that this is a random cluster, but not the one that includes all the photos. You can click on the icon of the person with the cross, and the cluster will be hidden. You can then name all the faces individually in the file or photo side panel. This is complicated if it is a very large cluster, because then you must add one by one.

**Comment by matiasdelellis** [comment]
There is a new model in the latest version, which theoretically should have better results since it was trained with more Asian people, however I don't know if this is your problem. 🤔

**Comment by Cebrain** [comment]
> ok.. You have two options.. If you have faces with strange positions (Not frontal) and you are using model 1, I recommend using model 4 and you will have much better results.
> 
> If they are childrens, or non-Caucasian/Asian people, the model we use has problems identifying these people. This model simply cannot differentiate them well.. 🤦🏻 It is a big problem but there is still no better model. 😞
> 
> In both cases you can try to reduce the grouping threshold and the minimum confidence and recluster again.
> 
> Then, just assuming that this is a random cluster, but not the one that includes all the photos. You can click on the icon of the person with the cross, and the cluster will be hidden. You can then name all the faces individually in the file or photo side panel. This is complicated if it is a very large cluster, because then you must add one by one.

thanks for response and sorry for the late reply.

Sadly nothing happened in my case. The pictures are mostly from european people and not many children.
There are many different pictures with frontal images and far away. 

The strange thing was that as i remember, all these pictures was already grouped with other people faces.
Suddenly this single People Group appeared (1000 pictures of my 8000).

Is it possible to destroy this group completely and face-recognition rescan the pictures?

**Comment by matiasdelellis** [comment]
It's strange that you have only one group that big. The reason for maintaining the current clustering algorithm is to avoid accumulating errors by making simple errors-

What values do you have in Clustering threshold and Minimum confidence?? By default it is 0.4 and 0.99. Test with 0.3 and 0.9

**Comment by Cebrain** [comment]
This is my current setup, it is possible that i messed something up with these settings a longer time ago.

![image](https://github.com/matiasdelellis/facerecognition/assets/78339531/b3a0e8e8-9c74-4bcb-8c8d-17e1702342a2)

So person stats are about:
Myself 1200 pictures
Person 2 1100 pictures
Person 3 1000 pictures
Then the broken picture group with 850 pictures
Person 4 200 pictures 
and go on.

**Comment by matiasdelellis** [comment]
With clustering threshold 0.4 you should already see a big difference.

**Comment by Cebrain** [comment]
Can i rescan only this group after setting to another value or do i need to reset everything?

**Comment by matiasdelellis** [comment]
No...It is not necessary..  it only affects grouping. There will be smaller clusters but of greater quality.

Maybe you should reset the clustering (`occ face:reset --clustering`)  to start renaming from scratch.

**Comment by Cebrain** [comment]
Ok, feedback is already here 😄 

Nothing really changed, but the Group now jumped from 850 pictures to 1250 pictures 😓 
But i recognize one thing, the group has mostly pictures from faces/people from the side.

**Comment by matiasdelellis** [comment]
> Nothing really changed, but the Group now jumped from 850 pictures to 1250 pictures 😓

D'Oh!. It doesn't make sense, but I believe you... 🙈 

> But i recognize one thing, the group has mostly pictures from faces/people from the side.

Maybe by analyzing from scratch with the last update and same model you can have an improvement, since I added a small undocumented change to improve these issues.

* https://github.com/matiasdelellis/facerecognition/commit/2f0f3e07fb1247b381679c7c2655fe5cfdfc0828#r142293734

But I honestly don't think it's worth it. Personally I would try to hide this cluster and eventually use the side panel to name each face little by little.

**Comment by Cebrain** [comment]
Still thanks for help :) 
Maybe when i have some time i will reset the faces. For the moment i live with it
