### ISSUE TITLE
Assigning parts of cluster to different person

### ISSUE THREAD

**Issue by Ang3er** [matiasdelellis/facerecognition#754]
Inside a cluster I would like to move a part (half of it) to a different person. My problem, both of my kids in young age are grouped as the same person. I can only change the person of the complete cluster or by selecting parts of it deleting the pictures or moving g them to an album.
Is there a way of assigning a selected list of pictures from one cluster to another.
I would hate to reset my clustering and "just" adjust the similarity value to the lowest, to get more cluster from beginning on.

Thanks

**Comment by vwbusguy** [comment]
I have four young kids and close to 200k pictures and am definitely interested in this as well.

**Comment by Ang3er** [comment]
I have found a solution for that. You can review the cluster per person in your private section of Nextcloud. This helped me to rename a cluster persona

**Comment by Ang3er** [comment]
Closed

**Comment by vwbusguy** [comment]
Yes, that's per-cluster.  I believe the OP is suggesting splitting a cluster instead of renaming the whole cluster.  For example, it's common that it can't quite tell my kids apart so I end up with clusters that are mostly one kid with but with some siblings and cousins in the same cluster.  It's a lot of extra clicks to assign them to a person then go back to Memories and try to find the wrongly tagged ones to fix them.  It would be nice to at a minimum be able to have an option to remove people from the cluster before renaming.
