### ISSUE TITLE
Personal => Face Recognition page result in error: the Uncaught EvalError: Refused to evaluate a string as JavaScript

### ISSUE THREAD

**Issue by SlavikCA** [matiasdelellis/facerecognition#95]
I just installed the app manually on my system:
- Ubuntu 16.04
- Nextcloud 15

And when opening `Personal => Face Recognition` in the browser (Chrome 71), I see this error in the console:
```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' 
is not an allowed source of script in the following Content Security Policy directive:
"script-src 'nonce-d0FNdFhKT3pqc2F4NHRsWWV0UERhclVPb3FHYVdyNmVOdWE4U1g3N2NBaz06aGxWQUphRGR2NEhEcHZJTU1iaUdDUFpoODVueWFkZmtYYmFNY0N5Q0NWcz0='".

    at JavaScriptCompiler.Function (<anonymous>)
    at JavaScriptCompiler.createFunctionContext (handlebars.js?v=27e5d68a-4:3562)
    at JavaScriptCompiler.compile (handlebars.js?v=27e5d68a-4:3450)
    at JavaScriptCompiler.compileChildren (handlebars.js?v=27e5d68a-4:4102)
    at JavaScriptCompiler.compile (handlebars.js?v=27e5d68a-4:3405)
    at JavaScriptCompiler.compileChildren (handlebars.js?v=27e5d68a-4:4102)
    at JavaScriptCompiler.compile (handlebars.js?v=27e5d68a-4:3405)
    at JavaScriptCompiler.compileChildren (handlebars.js?v=27e5d68a-4:4102)
    at JavaScriptCompiler.compile (handlebars.js?v=27e5d68a-4:3405)
    at compileInput (handlebars.js?v=27e5d68a-4:3249)
```

And way to fix it?

**Comment by SlavikCA** [comment]
ok, this error has nothing to do with Face Recognition.

It was caused by some HTTP headers.

Fixed by adding this to Apache config in .htaccess:
```
    Header set Content-Security-Policy "default-src 'self';"
    Header set Content-Security-Policy "style-src 'self' 'unsafe-inline';"
```

That's taken from the forum here:  
https://help.nextcloud.com/t/nextcloud-13-0-4-doesnt-work-with-chrome-and-firefox-works-only-with-ie/33466/8

**Comment by svolgmann** [comment]
I still stuck in the same problem with
- Nextcloud 15.0.2
- facerecognition 6e5dc95 

Adding the headers in /var/www/nextcloud/.htaccess don't work out for me. Any other suggestion?

**Comment by svolgmann** [comment]
Yes, the js deps are there:
`-rw-r--r-- 1 www-data www-data 159586 Nov 20  2015 /var/www/nextcloud/apps/facerecognition/js/handlebars.js`

The error looks pretty much the same as above in the console:
`handlebars.js?v=ca7d9b3a:3562 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'nonce-U3pRNVE1alJqWlE5TUZCVnJVM0Y2Y0liTUJBblg3dmt5bDQ2T2ZLYk5jRT06RG1GdmNxNzYyOWhIZUdBOHl3ejhuL3Q1WmlWRUJzcVZ2REZXZE1iUlJ1ND0='".`

    at JavaScriptCompiler.Function (<anonymous>)
    at JavaScriptCompiler.createFunctionContext (handlebars.js?v=ca7d9b3a:3562)
    at JavaScriptCompiler.compile (handlebars.js?v=ca7d9b3a:3450)
    at JavaScriptCompiler.compileChildren (handlebars.js?v=ca7d9b3a:4102)
    at JavaScriptCompiler.compile (handlebars.js?v=ca7d9b3a:3405)
    at JavaScriptCompiler.compileChildren (handlebars.js?v=ca7d9b3a:4102)
    at JavaScriptCompiler.compile (handlebars.js?v=ca7d9b3a:3405)
    at JavaScriptCompiler.compileChildren (handlebars.js?v=ca7d9b3a:4102)
    at JavaScriptCompiler.compile (handlebars.js?v=ca7d9b3a:3405)
    at compileInput (handlebars.js?v=ca7d9b3a:3249)
`createFunctionContext @ handlebars.js?v=ca7d9b3a:3562
  compile @ handlebars.js?v=ca7d9b3a:3450
  compileChildren @ handlebars.js?v=ca7d9b3a:4102
  compile @ handlebars.js?v=ca7d9b3a:3405
  compileChildren @ handlebars.js?v=ca7d9b3a:4102
  compile @ handlebars.js?v=ca7d9b3a:3405
  compileChildren @ handlebars.js?v=ca7d9b3a:4102
  compile @ handlebars.js?v=ca7d9b3a:3405
  compileInput @ handlebars.js?v=ca7d9b3a:3249
  ret @ handlebars.js?v=ca7d9b3a:3256
  renderContent @ personal.js?v=ca7d9b3a:83
  (anonymous) @ personal.js?v=ca7d9b3a:128
  j @ core.js?v=ca7d9b3a:2
  fireWith @ core.js?v=ca7d9b3a:2
  ready @ core.js?v=ca7d9b3a:2
  I @ core.js?v=ca7d9b3a:2`

Could it be, that nextcloud v15 needs to have precompiled templates now?

**Comment by SlavikCA** [comment]
I'm on NextCloud 15. It's working for me

**Comment by svolgmann** [comment]
See here https://github.com/nextcloud/server/issues/13205 this sounds related. I reinstall this repo (https://github.com/matiasdelellis/facerecognition) with all the deps, but still stuck in the same problem. 

The only view component which is working, is the overview page:

![bildschirmfoto 2019-01-29 um 22 04 29](https://user-images.githubusercontent.com/5967258/51940299-eb2ab780-2411-11e9-885c-2e33cfdea727.png)

**Comment by matiasdelellis** [comment]
Ohh.. Considering that handlebars are in the core of NC, let's try using this version.

Test replace:
https://github.com/matiasdelellis/facerecognition/blob/master/templates/settings/personal.php#L2

WIth:
> vendor_script('facerecognition', 'handlebars');

**Comment by svolgmann** [comment]
I just replace the code, but then it's looking for handlebars.js in apps/facerecognition/vendor/handlebars.js?v=a32194fb

If I copy the file there, i will get the same error as before.

Weird is the tutorial (https://docs.nextcloud.com/server/15/developer_manual/app/tutorial.html#adding-javascript-and-css) wich is also describing the same mechanism.

**Comment by matiasdelellis** [comment]
Well,
After an interesting discussion in another application, finally update to version 15.. I Test the last branch, and it works correctly.
